# Generated by Django 5.2.5 on 2025-12-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udemy_id', models.PositiveIntegerField(unique=True, verbose_name='Udemy Course ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('url', models.URLField(max_length=1000, verbose_name='Course URL')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Image URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('instructor_name', models.CharField(blank=True, max_length=200, verbose_name='Instructor Name')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='Language')),
                ('total_lectures', models.PositiveIntegerField(default=0, verbose_name='Total Lectures')),
                ('total_chapters', models.PositiveIntegerField(default=0, verbose_name='Total Chapters')),
                ('encrypted_videos_count', models.PositiveIntegerField(default=0, verbose_name='Encrypted Videos Count')),
                ('is_enrolled', models.BooleanField(default=False, verbose_name='Is Enrolled')),
                ('is_subscriber_content', models.BooleanField(default=False, verbose_name='Is Subscriber Content')),
                ('available_subtitles', models.JSONField(default=dict, help_text='Available subtitle languages and their counts', verbose_name='Available Subtitles')),
                ('course_data', models.JSONField(default=dict, help_text='Complete course structure data from Udemy API', verbose_name='Course Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses_course',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udemy_id', models.PositiveIntegerField(verbose_name='Udemy Chapter ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('lecture_count', models.PositiveIntegerField(default=0, verbose_name='Lecture Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'courses_chapter',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udemy_id', models.PositiveIntegerField(verbose_name='Udemy Lecture ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('lecture_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('quiz', 'Quiz'), ('practice', 'Practice'), ('file', 'File'), ('url', 'URL')], default='video', max_length=20, verbose_name='Lecture Type')),
                ('quality', models.CharField(choices=[('Auto', 'Auto'), ('144', '144p'), ('240', '240p'), ('360', '360p'), ('480', '480p'), ('720', '720p'), ('1080', '1080p'), ('Highest', 'Highest'), ('Lowest', 'Lowest'), ('Attachment', 'Attachment'), ('Subtitle', 'Subtitle'), ('NotFound', 'Not Found')], default='Auto', max_length=20, verbose_name='Quality')),
                ('source_url', models.URLField(blank=True, max_length=2000, verbose_name='Source URL')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Is Encrypted')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('asset_data', models.JSONField(default=dict, help_text='Complete asset data from Udemy API', verbose_name='Asset Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.chapter')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'db_table': 'courses_lecture',
                'ordering': ['chapter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LectureAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('attachment_type', models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('article', 'Article')], default='file', max_length=20, verbose_name='Type')),
                ('source_url', models.URLField(blank=True, max_length=2000, verbose_name='Source URL')),
                ('external_url', models.URLField(blank=True, max_length=2000, verbose_name='External URL')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Filename')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lecture')),
            ],
            options={
                'verbose_name': 'Lecture Attachment',
                'verbose_name_plural': 'Lecture Attachments',
                'db_table': 'courses_lecture_attachment',
                'ordering': ['lecture', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LectureSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('language_label', models.CharField(max_length=100, verbose_name='Language Label')),
                ('source_url', models.URLField(max_length=2000, verbose_name='Source URL')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Is Auto Generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='courses.lecture')),
            ],
            options={
                'verbose_name': 'Lecture Subtitle',
                'verbose_name_plural': 'Lecture Subtitles',
                'db_table': 'courses_lecture_subtitle',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Last Accessed')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('completion_percentage', models.FloatField(default=0.0, verbose_name='Completion Percentage')),
                ('is_downloaded', models.BooleanField(default=False, verbose_name='Is Downloaded')),
                ('download_path', models.CharField(blank=True, max_length=1000, verbose_name='Download Path')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='courses.course')),
            ],
            options={
                'verbose_name': 'User Course',
                'verbose_name_plural': 'User Courses',
                'db_table': 'courses_user_course',
                'ordering': ['-last_accessed'],
            },
        ),
    ]
