# Generated by Django 5.2.5 on 2025-12-24 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'udemy_id')},
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('chapter', 'udemy_id')},
        ),
        migrations.AlterUniqueTogether(
            name='lecturesubtitle',
            unique_together={('lecture', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
    ]
