# Generated by Django 5.2.5 on 2025-12-24 19:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('attachment', 'Attachment'), ('subtitle', 'Subtitle')], max_length=20, verbose_name='Item Type')),
                ('filename', models.CharField(max_length=500, verbose_name='Filename')),
                ('source_url', models.URLField(max_length=2000, verbose_name='Source URL')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('encrypted', 'Encrypted')], default='pending', max_length=20, verbose_name='Status')),
                ('progress_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Progress Percentage')),
                ('file_path', models.CharField(blank=True, max_length=1000, verbose_name='File Path')),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes', verbose_name='File Size')),
                ('downloaded_size', models.BigIntegerField(default=0, help_text='Size in bytes', verbose_name='Downloaded Size')),
                ('quality', models.CharField(blank=True, max_length=20, verbose_name='Quality')),
                ('format', models.CharField(blank=True, max_length=50, verbose_name='Format')),
                ('download_speed', models.FloatField(default=0.0, help_text='Speed in bytes/second', verbose_name='Download Speed')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Is Encrypted')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Download Item',
                'verbose_name_plural': 'Download Items',
                'db_table': 'downloads_item',
                'ordering': ['download_task', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('total_downloads', models.PositiveIntegerField(default=0, verbose_name='Total Downloads')),
                ('successful_downloads', models.PositiveIntegerField(default=0, verbose_name='Successful Downloads')),
                ('failed_downloads', models.PositiveIntegerField(default=0, verbose_name='Failed Downloads')),
                ('total_data_downloaded', models.BigIntegerField(default=0, help_text='Size in bytes', verbose_name='Total Data Downloaded')),
                ('average_speed', models.FloatField(default=0.0, help_text='Speed in bytes/second', verbose_name='Average Speed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
            ],
            options={
                'verbose_name': 'Download Session',
                'verbose_name_plural': 'Download Sessions',
                'db_table': 'downloads_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_subtitle', models.CharField(blank=True, help_text='Selected subtitle language for download', max_length=100, verbose_name='Selected Subtitle')),
                ('download_type', models.IntegerField(choices=[(0, 'Both (Videos + Attachments)'), (1, 'Only Lectures'), (2, 'Only Attachments')], default=0, verbose_name='Download Type')),
                ('video_quality', models.CharField(default='Auto', max_length=20, verbose_name='Video Quality')),
                ('enable_range_download', models.BooleanField(default=False, verbose_name='Enable Range Download')),
                ('download_start', models.PositiveIntegerField(default=1, verbose_name='Download Start')),
                ('download_end', models.PositiveIntegerField(default=0, verbose_name='Download End')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('downloading', 'Downloading'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('progress_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Progress Percentage')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total Items')),
                ('downloaded_items', models.PositiveIntegerField(default=0, verbose_name='Downloaded Items')),
                ('failed_items', models.PositiveIntegerField(default=0, verbose_name='Failed Items')),
                ('encrypted_items', models.PositiveIntegerField(default=0, verbose_name='Encrypted Items')),
                ('download_path', models.CharField(max_length=1000, verbose_name='Download Path')),
                ('total_size', models.BigIntegerField(default=0, help_text='Size in bytes', verbose_name='Total Size')),
                ('downloaded_size', models.BigIntegerField(default=0, help_text='Size in bytes', verbose_name='Downloaded Size')),
                ('download_speed', models.FloatField(default=0.0, help_text='Speed in bytes/second', verbose_name='Download Speed')),
                ('estimated_time_remaining', models.DurationField(blank=True, null=True, verbose_name='Estimated Time Remaining')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Max Retries')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery Task ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Download Task',
                'verbose_name_plural': 'Download Tasks',
                'db_table': 'downloads_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion Date')),
                ('download_path', models.CharField(max_length=1000, verbose_name='Download Path')),
                ('encrypted_videos_count', models.PositiveIntegerField(default=0, verbose_name='Encrypted Videos Count')),
                ('total_size', models.BigIntegerField(default=0, help_text='Size in bytes', verbose_name='Total Size')),
                ('selected_subtitle', models.CharField(blank=True, max_length=100, verbose_name='Selected Subtitle')),
                ('video_quality', models.CharField(max_length=20, verbose_name='Video Quality')),
                ('download_type', models.IntegerField(default=0, verbose_name='Download Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='courses.course')),
            ],
            options={
                'verbose_name': 'Download History',
                'verbose_name_plural': 'Download History',
                'db_table': 'downloads_history',
                'ordering': ['-updated_at'],
            },
        ),
    ]
