# Generated by Django 5.2.5 on 2025-12-24 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('downloads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lecture'),
        ),
        migrations.AddField(
            model_name='downloadsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tasks', to='courses.course'),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='download_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_items', to='downloads.downloadtask'),
        ),
        migrations.AlterUniqueTogether(
            name='downloadhistory',
            unique_together={('user', 'course')},
        ),
    ]
